---
- include: base.yml

- hosts: mysql
  sudo: yes
  roles:
    - role: mysql
      tags:
        - mysql

- hosts: rabbit
  sudo: yes
  roles:
    - role: rabbit
      tags:
        - rabbit

- hosts: keystone
  sudo: yes
  roles:
    - role: keystone
      tags:
        - keystone

