---
# You may have more setup actions you'd like to take here

- include: base.yml


- hosts: controller
  sudo: yes
  roles:
    - role: controller
      tags:
        - controller




# You may have more teardown actions you'd like to take here
