---
- apt: name=rabbitmq-server state=present
  notify: 
    - set rabbit passwd
    - restart rabbit


- name: ensure rabbit is started and enabled
  service: name=rabbitmq-server state=started enabled=true
