---
- name: install virtual box gust utils
  apt: name={{ item }} state=present
  with_items:
  - mysql-server

# unfortunately fails on subsequent runs... can we make this idempotent?
- name: setup the default root password
  mysql_user: login_user=root login_password="" name=root password=supersecret
  ignore_errors: true

- name: test doing a dthing with my new superpower
  mysql_user: login_user=root login_password=supersecret name=bob password=12345 priv=*.*:ALL state=present
