---
- name: Run the "apt-get update"
  apt: update_cache=yes

- name: Update all packages to the latest version
  apt: upgrade=dist

- name: install virtual box gust utils
  apt: name=virtualbox-guest-utils state=present

# settings to help keep ssh latency low
- name: set UseDNS no in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="UseDNS" line="UseDNS no"
  notify: restart sshd

- name: set GSSAPIAuthentication no in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="GSSAPIAuthentication" line="GSSAPIAuthentication no"
  notify: restart sshd

- name: install /etc/hosts file
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
