---
- name: install client tools
  apt: name={{ item }} state=installed
  with_items:
    - python-dev
    - python-pip

- name: install all of the client libs
  pip: name=python-{{ item }}client state=present
  with_items:
    - ceilometer
    - cinder
    - glance
    - heat
    - keystone
    - neutron
    - nova
    - sahara
    - swift
    - trove
    - openstack
